development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: db
  database: ratings_dev
  pool: 5
  username: ratings
  password: password
  socket: /var/run/mysqld/mysqld.sock
  strict: false

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: db
  database: ratings_test
  pool: 5
  username: ratings
  password: password
  socket: /var/run/mysqld/mysqld.sock
  strict: false

