test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: localhost
  database: ratings_test
  pool: 5
  username: ratings
  password: password
  socket: /var/run/mysqld/mysqld.sock
  strict: false

