ALL: &ALL
  www_db:
    host: 127.0.0.1
    database: www_development
    username: username
    password: password
    encoding: utf8
  hasher: "Digest::MD5.hexdigest(Digest::MD5.hexdigest(salt[0,15] + pass + salt[17,15]))"
  google_site_verification: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
  mailgun:
    password: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    secret: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    public: pubkey-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

test:
  <<: *ALL
  secret_key_base: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
