name: Main

on: [push]

jobs:
  test:
    runs-on: ubuntu-22.04

    services:
      db:
        image: mysql:5.7
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_DATABASE: 'ratings_test'
          MYSQL_USER: 'ratings'
          MYSQL_PASSWORD: 'password'
          MYSQL_ROOT_PASSWORD: 'password'
          MYSQL_DEBUG: false
        ports: ['3306:3306']
    env:
      RAILS_ENV: test
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: prepare config
        run: |
          cp config/database.github-actions.yml config/database.yml

      - name: install dependencies
        run: |
          sudo apt-get install -y nodejs firefox
          wget https://github.com/mozilla/geckodriver/releases/download/v0.32.0/geckodriver-v0.32.0-linux64.tar.gz
          sudo tar -xzvf geckodriver-v0.32.0-linux64.tar.gz -C /usr/local/bin
          sudo chmod +x /usr/local/bin/geckodriver

      - name: Run tests
        run: |
          bundler exec rspec spec/

