name: Main

on: [push]

jobs:
  test:
    runs-on: ubuntu-22.04

    services:
      db:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: 'ratings_test'
          MYSQL_USER: 'ratings'
          MYSQL_PASSWORD: 'password'
          MYSQL_ROOT_PASSWORD: 'password'
          MYSQL_DEBUG: false
    env:
      RAILS_ENV: test
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: prepare config
        run: |
          cp config/database.github-actions.yml config/database.yml

      - name: Run tests
        run: |
          bundler exec rspec spec/

